In [1]:
import numpy as np
import pandas as pd

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.tree import DecisionTreeClassifier

In [5]:
df = pd.read_csv('tested.csv')

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [7]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [10]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Survived']),
                                                 df['Survived'],
                                                 test_size=0.2,
                                                random_state=42)

In [11]:
X_train.head()

     Pclass   Sex   Age  SibSp  Parch     Fare Embarked
336       2  male  32.0      0      0  13.0000        S
31        2  male  24.0      2      0  31.5000        S
84        2  male   NaN      0      0  10.7083        Q
287       1  male  24.0      1      0  82.2667        S
317       2  male  19.0      0      0  10.5000        S

In [12]:
X_train.sample(5)

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
352       2    male  18.0      0      0  73.5000        S
35        3    male  18.5      0      0   7.2292        C
159       3  female  26.0      0      2  13.7750        S
38        3    male  25.0      0      0   9.5000        S
189       2    male  40.0      0      0  13.0000        S

In [16]:
trf1 = ColumnTransformer([
    ('impute_age',SimpleImputer(),[2]),
    ('impute_embarked',SimpleImputer(strategy='most_frequent'),[6])
],remainder='passthrough')

In [19]:
trf2 = ColumnTransformer([
    ('ohe_sex_embarked',OneHotEncoder(sparse_output=True, handle_unknown ='ignore'),[1,6])
],remainder='passthrough')

In [20]:
trf3 = ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,8))
])

In [23]:
trf4 = SelectKBest(score_func=chi2,k=5)

In [24]:
trf5 = DecisionTreeClassifier()

# Create Pipeline

In [25]:
pipe = Pipeline([
    ('trf1',trf1),
    ('trf2',trf2),
    ('trf3',trf3),
    ('trf4',trf4),
    ('trf5',trf5)
])

# Pipeline Vs make_pipeline

pipeline requires nameing of steps , make pipeline does not
same applies to columntransformer vs make columntransformer

In [26]:
# Alternate syntax
pipe = make_pipeline(trf1,trf2,trf3,trf4,trf5)

In [27]:
#train
pipe.fit(X_train,y_train)

ValueError: For a sparse output, all columns should be a numeric or convertible to a numeric.

# Explore the pipeline

In [34]:
pipe.named_steps

{'columntransformer-1': ColumnTransformer(remainder='passthrough',
                   transformers=[('impute_age', SimpleImputer(), [2]),
                                 ('impute_embarked',
                                  SimpleImputer(strategy='most_frequent'),
                                  [6])]),
 'columntransformer-2': ColumnTransformer(remainder='passthrough',
                   transformers=[('ohe_sex_embarked',
                                  OneHotEncoder(handle_unknown='ignore'),
                                  [1, 6])]),
 'columntransformer-3': ColumnTransformer(transformers=[('scale', MinMaxScaler(), slice(0, 8, None))]),
 'selectkbest': SelectKBest(k=5, score_func=<function chi2 at 0x000001F48A345580>),
 'decisiontreeclassifier': DecisionTreeClassifier()}

In [38]:
pipe.named_steps['trf1'].transformers_

KeyError: 'trf1'

In [36]:
from sklearn import set_config
set_config(display='diagram')

In [37]:
y_pred = pipe.predict(X_test)

ValueError: For a sparse output, all columns should be a numeric or convertible to a numeric.

In [39]:
y_pred

NameError: name 'y_pred' is not defined

In [30]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

NameError: name 'y_pred' is not defined

Cross validaing using pipeline

In [40]:
from sklearn.model_seleection import cross_val_score
cross_val_score(pipe, X_train, y_train, cv=5, scoring='accuracy').mean()

ModuleNotFoundError: No module named 'sklearn.model_seleection'

# Grid search using pipeline

In [ ]:
params= {
    'trf5'_max_depth':[1,2,3,4,5,,None]
}

In [41]:
grid.best_score_

NameError: name 'grid' is not defined

In [42]:
grid.best_params_

NameError: name 'grid' is not defined

# Exporting the pipeline

In [44]:
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))