In [67]:
import numpy as np
import pandas as pd 

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [68]:
df = pd.read_csv('tested.csv')

In [69]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [70]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [71]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  34.5      0      0   7.8292        Q
1         1       3  female  47.0      1      0   7.0000        S
2         0       2    male  62.0      0      0   9.6875        Q
3         0       3    male  27.0      0      0   8.6625        S
4         1       3  female  22.0      1      1  12.2875        S

In [72]:
# step-1 train/test/split
X_train,X_test,y_train,y_test =train_test_split(df.drop(columns=['Survived']),
                                                df['Survived'],
                                                test_size=0.2,
                                                random_state=42)

In [73]:
X_train.head(2)

     Pclass   Sex   Age  SibSp  Parch  Fare Embarked
336       2  male  32.0      0      0  13.0        S
31        2  male  24.0      2      0  31.5        S

In [74]:
y_train.head()

336    0
31     0
84     0
287    0
317    0
Name: Survived, dtype: int64

In [75]:
df.isnull().sum()

Survived     0
Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [76]:
si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')
X_train_age = si_age.fit_transform(X_train[['Age']])
X_train_embarked = si_embarked.fit_transform(X_train[['Embarked']])
X_test_age = si_age.transform(X_test[['Age']])
X_test_embarked = si_embarked.transform(X_test[['Embarked']])

In [79]:
 X_train_embarked

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 334 stored elements and shape (334, 3)>

In [80]:
ohe_sex = OneHotEncoder(sparse_output = True , handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse_output = True , handle_unknown='ignore')
X_train_sex = ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked = ohe_embarked.fit_transform(X_train_embarked)
X_test_sex = ohe_sex.transform(X_test[['Sex']])                                        
X_test_embarked = ohe_embarked.transform(X_test_embarked)

TypeError: Sparse data was passed, but dense data is required. Use '.toarray()' to convert to a dense numpy array.

In [49]:
X_train.head(2)

     Pclass   Sex   Age  SibSp  Parch  Fare Embarked
336       2  male  32.0      0      0  13.0        S
31        2  male  24.0      2      0  31.5        S

In [50]:
X_train_embarked

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 334 stored elements and shape (334, 3)>

In [58]:
X_train_rem = X_train.drop(columns=['Sex','Age','Embarked'])

In [85]:
X_test_rem = X_test.drop(columns=['Sex','Age','Embarked'])

In [87]:
X_train_transformed = np.concatenate((X_train_rem,X_train_age,X_train_sex,X_train_embarked),axis=1)
X_test_transformed = np.concatenate((X_test_rem,X_test_age,X_test_sex,X_test_embarked),axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 2 has 0 dimension(s)

In [88]:
X_train_transformed = np.concatenate(
    (X_train_rem, X_train_age, X_train_sex, X_train_embarked),
    axis=1
)

X_test_transformed = np.concatenate(
    (X_test_rem, X_test_age, X_test_sex, X_test_embarked),
    axis=1
)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 2 has 0 dimension(s)

In [89]:
X_train_transformed

NameError: name 'X_train_transformed' is not defined

In [ ]:
X_train_transformed.shape

In [61]:
clf = DecisionTreeClassifier()
clf.fit(X_train_transformed,y_train)

NameError: name 'X_train_transformed' is not defined

In [90]:
y_pred = clf.predict(X_test_transformed)
y_pred

NameError: name 'X_test_transformed' is not defined

In [83]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

NameError: name 'y_pred' is not defined

In [93]:
import pickle
import numpy as np

In [95]:
ohe_sex = pickle.load(open('model/ohe_sex.pkl','rb'))
ohe_embarked = pickel.load(open('model/ohe_embarked.pkl','rb'))
clf = pickel.load(open('model/clf.pkl','rb'))

FileNotFoundError: [Errno 2] No such file or directory: 'model/ohe_sex.pkl'